//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Görsel_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkulYönetimi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OkulYönetimi()
        {
            this.YönetimDers = new HashSet<YönetimDers>();
        }
    
        public int ID { get; set; }
        public string Ad_Soyad { get; set; }
        public string Görevi { get; set; }
        public string Görev_Tipi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YönetimDers> YönetimDers { get; set; }
    }
}
