//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Görsel_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class YönetimDers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YönetimDers()
        {
            this.ÖDers = new HashSet<ÖDers>();
        }
    
        public int ID { get; set; }
        public string Ders_Adı { get; set; }
        public string Ders_Kredisi { get; set; }
        public Nullable<int> Okul_Yönetim_ID { get; set; }
    
        public virtual OkulYönetimi OkulYönetimi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖDers> ÖDers { get; set; }
    }
}
