//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Görsel_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÖDers
    {
        public int ID { get; set; }
        public Nullable<int> Ders_ID { get; set; }
        public Nullable<int> Öğrenci_ID { get; set; }
    
        public virtual Öğrenci Öğrenci { get; set; }
        public virtual YönetimDers YönetimDers { get; set; }
    }
}
