//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Görsel_Vize
{
    using System;
    using System.Collections.Generic;
    
    public partial class Öğrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Öğrenci()
        {
            this.ÖDers = new HashSet<ÖDers>();
        }
    
        public int ID { get; set; }
        public string Ad_Soyad { get; set; }
        public string Kayıt_Tarihi { get; set; }
        public string Öğrenci_No { get; set; }
        public Nullable<System.DateTime> Doğum_Tarihi { get; set; }
        public string Bölüm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ÖDers> ÖDers { get; set; }
    }
}
